### ISSUE TITLE
chown: /fah: Operation not permitted

### ISSUE THREAD

**Issue by chrisjohnson00** [pcktdmp/charts#34]
Running the latest chart (2.5.3) causes the init container to fail to complete on my cluster.
I manually edited the init container command and removed the `chown` because it shouldn't be needed, and it is working fine for me now.  I'll PR the chart fix shortly.

----
Looking at the history of the repo, I need to add some details here.
I rebuilt my k8s cluster this week and FAH wouldn't work for me on the new setup.  
I was running k8s 1.17 with this chart fine, I'm not sure what specific chart version it was.  
I'm running k8s 1.18 now. My storage is backed by NFS.
I understand why you are copying the config file via an init container, however I don't believe you need to chmod the directory.  Perhaps you had a case where it changed from one uid:gui to a new one?  
One thing I do notice is that you put the `securityContext` definition in the `container` block, rather than under the `spec` block.  Perhaps if there's a need for the `chmod` in your experience, an alternate solution might be to move the `securityContext` to `spec` so that it applies to the init container also, thus making the `chmod` no longer needed.

**Comment by pcktdmp** [comment]
Thanks again for the contribution.
Released and also removed PUID and PGID environment variables since they are not needed: https://github.com/pcktdmp/charts/commit/7e3ddfc585f7f43b0813e22a0ad9e10e06b02ee6
