### ISSUE TITLE
Incorrect security context for init container

### ISSUE THREAD

**Issue by lindhe** [pcktdmp/charts#38]
I cannot get the client to run with the default security context. The pod is stuck in a `CrashLoopBackOff` and will not start because the init container is failing. When I inspect its log, I find:

```console
$ kubectl logs fahclient-0 -c init
cp: can't create '/fah/config.xml': Permission denied
```

So I tried to change the `.Values.podSecurityContext` from
```yaml
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 9999
  runAsGroup: 9999
```
to
```yaml
podSecurityContext:
  # runAsNonRoot: true
  # runAsUser: 9999
  # runAsGroup: 9999
```
and that made it work.

I guess we need to give the init container permissions to write.

It works fine for me in minikube but not in AKS, which surprised me. Do you know if minikube treats security context differently?

Are you able to reproduce this? In what Kubernetes engine have you tried to run it before?

## Versions

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.15", GitCommit:"73dd5c840662bb066a146d0871216333181f4b64", GitTreeState:"clean", BuildDate:"2021-01-15T02:41:45Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T16:06:08Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Chart version: `2.5.4`

**Comment by pcktdmp** [comment]
Hi @lindhe, 

Cool that you use this helm chart and donating compute capacity for this cause! :-)
Does version `2.5.3` work for you?

Yours,

Serge

**Comment by lindhe** [comment]
Yes it does!

**Comment by pcktdmp** [comment]
Ok cool, then the issue was probably introduced with the following commit: cfe2611cf9108231964d6f3c27e796dcee71b309

I'll dive into it when I have some time, it's weird that this specifically pops up with AKS, it might just be related that Kubernetes `v1.19.6` simply doesn't support the construct anymore.

**Comment by pcktdmp** [comment]
@lindhe could you try to run `2.5.4` with `fsGroup: 9999` set? (with`kubectl edit statefulset ..`) 

```
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 9999
  runAsGroup: 9999
  fsGroup: 9999
```

If this fixes it I can merge and release :-)

This fix at least works on:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by lindhe** [comment]
Quite confusingly, I cannot reproduce the issue today. Huh. Unless you can reproduce it, let's mark this as closed until I figure out if I did something wrong the first time around...

**Comment by pcktdmp** [comment]
Did you try with fresh persistent volumes / complete new installation of the chart? The stateful set reuses storage and since you ran 2.5.3 it does not occur probably. 2.5.5 is released which should resolve the issue.

**Comment by lindhe** [comment]
I have unfortunately not had time to test it again. The cluster I ran it on
is no more either. My clusters come and go a lot, but I don't want to
promise to try it out anytime soon.
